language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 'stable'
after_install:
  - npm prune
script:
  - npm run lint
  - npm run test
after_success:
  - make dist
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
